[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "pysisyphus/version.py"

# pyright seems to choke on these big integral files
[tool.pyright]
exclude = ["pysisyphus/wavefunction/ints**"]
